name: Deploy a VPS

on: 
  push:
    branches:
      - docker-compose

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
      
      - name: Desplegar código al servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /ruta/de/tu/proyecto
            git pull origin main
            docker-compose up -d --build
